objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Match_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>billingpostelcode__c</fullName>
        <label>billingpostelcode</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>shippingpostelcode__c</fullName>
        <label>shippingpostelcode</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/accounthandlerclass1.cls
public class accounthandlerclass1 {
    public static void beforeUpdate(List<Account>newList){
        for(Account acc:newList){
        acc.Description ='Test description';

    }
    }
    public static void beforeInsert(List<Account>newList){
         for(Account acc : newList){
        if( acc.Match_Billing_Address__c == True)
            acc.billingpostelcode__c = acc.shippingpostelcode__c;
       
       
    }
    }
    public static void updateRelatedopp(List <Account> accList,Map<Id,Account>oldMap){
        List<Opportunity>opplist = new list<Opportunity>();
        set<Id>accIds = new set<Id>();
        for(Account acc: acclist){
            if(acc.Active__c=='No' && oldMap.get(acc.Id).Active__c=='Yes'){
                accIds.add(acc.Id);
            }
        }
        
    }
    
}